root: true
parser: "@typescript-eslint/parser"
plugins:
  - 'prettier'
  - '@typescript-eslint'
extends:
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
env:
  browser: true
  es6: true
  node: true
rules:
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: true
      semi: false
      arrowParens: avoid
  prefer-const: 2
  no-useless-escape: 0
